spring.application.name=langchain4j-demo
langchain4j.openai.client.timeout=60s

app.cli.enabled=true
app.chat.model-name=gpt-4o-mini
app.memory.max-messages=10
app.memory.max-tokens=2000
app.embedding.model-name=text-embedding-3-small
app.embedding.store-path=embedding-store.json
app.embedding.max-results=5
app.rag.max-results=5
app.document.splitter=recursive
app.document.max-chunk-size=200
app.document.max-overlap=20
